# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: environments.appstudio.redhat.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1alpha1", "v1beta1"]
      clientConfig:
        service:
          namespace: gitops
          name: gitops-appstudio-service-webhook-service
          path: /validate-appstudio-redhat-com-v1beta1-environment
