## Append samples you want in your CSV to this file as resources ##
resources:
- appstudio_v1alpha1_application.yaml
- appstudio_v1alpha1_component.yaml
- appstudio_v1alpha1_componentdetectionquery.yaml
- appstudio_v1alpha1_snapshotenvironmentbinding.yaml
- appstudio_v1alpha1_snapshot.yaml
- appstudio_v1alpha1_promotionrun.yaml
- appstudio_v1alpha1_environment.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
